version: "3.8"

services:

  continuous-curl-runner:
    image: ${REG}continuous-curl-runner:${BUILD_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      REQUESTS_JSON: ${REQUESTS_JSON}
      LOOP: "5"
      SELECTION: "random"