version: "3.8"

services:

  continuous-curl-runner:
    image: ${REG}continuous-curl-runner:${BUILD_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      REQUESTS_JSON: ${REQUESTS_JSON}
      REQUESTS_INTERVAL: "5"
      REQUESTS_SELECTION: "random"
      #REQUESTS_SELECTION: "all"
      test_user: "some_user"
      test_password1: "passwd1"
      test_password2: "passwd2"
      test_password3: "passwd3"

